"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
DB_PASSWORD = os.getenv("DB_PASSWORD")
SECRET_KEY = os.getenv("SECRET_KEY")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_NAME = os.getenv("EMAIL_NAME")
Y_CLIENTID = os.getenv("Y_CLIENTID")
Y_CLIENTSECRET = os.getenv("Y_CLIENTSECRET")
G_CLIENTID = os.getenv("G_CLIENTID")
G_CLIENTSECRET = os.getenv("G_CLIENTSECRET")
DEBUG = os.getenv("DEBUG") == "True"
# Build paths inside the project like this: BASE_DIR / 'subdir'.
LOGIN_URL = '/accounts/login/'  
LOGOUT_URL = '/accounts/logout/'
LOGIN_REDIRECT_URL = '/news/'  # на страницу новостей
LOGOUT_REDIRECT_URL = '/accounts/logout/'
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'django.contrib.sites',
    'django_filters',
    'protect',
    'sign',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.yandex',
    'news.apps.NewsConfig',
    
]
#DEFAULT_FROM_EMAIL = 'email_name'
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.cache.UpdateCacheMiddleware",

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    "django.middleware.cache.FetchFromCacheMiddleware",
]
ACCOUNT_TEMPLATE_EXTENSION = 'html'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ROOT_URLCONF = 'NewsPaper.urls'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': G_CLIENTID,
            'secret': G_CLIENTSECRET,
            'key': ''
        }
    },
    'yandex': {
        'APP': {
            'client_id': Y_CLIENTID,
            'secret': Y_CLIENTSECRET,
            'key': ''
        }
    }
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # ===== ФИЛЬТРЫ =====
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',  
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',  
        },
    },

   
    'formatters': {
       
        'console_simple': {
            'format': '%(asctime)s %(levelname)s %(message)s',
        },
       
        'console_warning': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s',
        },

        'console_error': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s',
            'exc_info': True,
        },
        'general': {
            'format': '%(asctime)s %(levelname)s %(module)s %(message)s',
        },
      
        'errors': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s',
        },
        
        'security': {
            'format': '%(asctime)s %(levelname)s %(module)s %(message)s',
        },
        
        'mail': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s',
        },
    },

    # ===== ОБРАБОТЧИКИ =====
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': ['require_debug_true'],
            'formatter': 'console_simple',
        },
        
        'general_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'general.log'),
            'filters': ['require_debug_false'],
            'formatter': 'general',
        },
       
        'errors_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'errors.log'),
            'formatter': 'errors',
        },
       
        'security_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'formatter': 'security',
        },
       
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'mail',
        },
    },

    # ===== ЛОГГЕРЫ =====
    'loggers': {
        
        'django': {
            'handlers': ['console', 'general_file'],
            'level': 'WARNING',
            'propagate': True,
        },
        
        'django.request': {
            'handlers': ['errors_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['errors_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.template': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'DEBUG',
            'propagate': False,  
        },
    },
}

WSGI_APPLICATION = 'NewsPaper.wsgi.application'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.path.join(BASE_DIR, "cache_files"),
        "TIMEOUT": 60*5
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': DB_PASSWORD,
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

ACCOUNT_FORMS = {'signup': 'sign.models.BasicSignupForm'}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [
    BASE_DIR / 'static' 
]
#celery settings
CELERY_BROKER_URL = 'redis://localhost:6378/0'  # Memurai на локальном порту 6379, база 0
CELERY_RESULT_BACKEND = 'redis://localhost:6378/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # адрес сервера Яндекс-почты для всех один и тот же
EMAIL_PORT = 587  # порт smtp сервера тоже одинаковый
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = EMAIL_NAME # ваше имя пользователя, например, если ваша почта user@yandex.ru, то сюда надо писать user, иными словами, это всё то что идёт до собаки
EMAIL_HOST_PASSWORD = EMAIL_PASSWORD  # пароль от почты
DEFAULT_FROM_EMAIL = EMAIL_NAME
